#ifndef SPRY_ENDPOINTS_ENUMS_GEN_H
#define SPRY_ENDPOINTS_ENUMS_GEN_H

typedef enum {
  SPRY_TYPE_STRING,
  SPRY_TYPE_BOOLEAN,
  SPRY_TYPE_INT8,
  SPRY_TYPE_UINT8,
  SPRY_TYPE_INT16,
  SPRY_TYPE_UINT16,
  SPRY_TYPE_INT32,
  SPRY_TYPE_UINT32,
  SPRY_TYPE_FLOAT32,
  SPRY_TYPE_FLOAT64,
} spry_type_t;

#endif
