#ifndef SPRY_FAULT_ENUMS_GEN_H
#define SPRY_FAULT_ENUMS_GEN_H

typedef enum {
  SPRY_CODE_INVALID,
  SPRY_CODE_UNAUTHENTICATED,
  SPRY_CODE_DENIED,
  SPRY_CODE_MISSING,
  SPRY_CODE_CONFLICT,
  SPRY_CODE_FAILED,
  SPRY_CODE_UNAVAILABLE,
  SPRY_CODE_TIMEOUT,
  SPRY_CODE_CANCELLED,
} spry_code_t;

#endif
